---
    - name: Add postgresql apt repository key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
    
    - name: Add postgresql apt repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        state: present
        update_cache: yes
    
    - name: Install postgresql
      apt:
        name: postgresql-11
        state: present
    
    - name: Install python-psycopg2
      apt:
        name: python-psycopg2
        state: present
    
    - name: Ensure postgresql is enabled running
      service:
        name: postgresql
        enabled: yes
        state: started
    
    - name: Change listen_addresses to '*'
      lineinfile:
        dest: /etc/postgresql/11/main/postgresql.conf
        regexp: "^#listen_addresses"
        line: "listen_addresses = '*'"
        state: present
        backup: yes
      notify:
        - restart postgresql
    
    - name: Configure pg_hba.conf
      template:
        src: ./templates/pg_hba.conf.j2
        dest: /etc/postgresql/11/main/pg_hba.conf
        owner: postgres
      notify:
        - restart postgresql

    - name: "Ensure the database {{ database_name }} is created"
      become: true
      become_user: postgres
      postgresql_db:
        name: '{{ database_name }}'
        encoding: UTF-8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
        template: template0

    - name: "Ensure the user {{ database_user }} has access to the database"
      become: true
      become_user: postgres
      postgresql_user:
        db: '{{ database_name }}'
        name: '{{ database_user }}'
        password: '{{ database_password }}'
        encrypted: yes
        priv: ALL